#!/usr/bin/env python3
"""
GGUF LLM Training Pipeline - Master CLI Orchestrator
Usage:
  python run_pipeline.py --mode sft --source sleep --steps 20
  python run_pipeline.py --mode dpo --source sleep --steps 20
  python run_pipeline.py --export-gguf
"""

import os
import sys
import argparse
import yaml

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from data_ingestion.sleep_dossier_collector import SleepDossierCollector
from data_ingestion.external_url_extractor import ExternalUrlExtractor
from data_ingestion.dataset_builder import DatasetBuilder
from data_ingestion.dataset_filter import DatasetFilter
from data_ingestion.curation_gatekeeper import CurationGatekeeper
from data_ingestion.rolling_passdown_manager import RollingPassdownManager
from data_ingestion.real_world_feeder import RealWorldSleepFeeder
from training.qlora_trainer import QLoRATrainer
from training.rl_agent_trainer import RLAgentTrainer
from training.safety_guardrails import SafetyGuardrails
from export.lora_merger import LoRAMerger
from export.gguf_exporter import GGUFExporter
from integration.cluster_bridge_connector import ClusterBridgeConnector
from integration.verification_harness import VerificationHarness

def main():
    parser = argparse.ArgumentParser(description="GGUF LLM Training Pipeline (QLoRA & Controlled RL)")
    parser.add_argument("--config", default="./config/training_config.yaml", help="Path to config file")
    parser.add_argument("--mode", choices=["sft", "dpo", "grpo", "full"], default="sft", help="Training mode")
    parser.add_argument("--source", choices=["sleep", "url", "upload", "all"], default="sleep", help="Data source")
    parser.add_argument("--url", default=None, help="External URL to ingest if source=url")
    parser.add_argument("--steps", type=int, default=20, help="Training step budget")
    parser.add_argument("--model", default=None, help="Hugging Face model ID or path")
    parser.add_argument("--skip-train", action="store_true", help="Skip training, run data/export only")
    parser.add_argument("--export-gguf", action="store_true", help="Export adapter to GGUF format")
    parser.add_argument("--quant", default="q4_k_m", choices=["q4_k_m", "q8_0", "all"], help="Quantization target")
    parser.add_argument("--promote", choices=["worker", "coordinator"], default=None, help="Promote tested model to cluster")
    # Dual-Gate Curation & Rolling Passdown CLI flags
    parser.add_argument("--review-pending", action="store_true", help="List samples waiting for Gate 2 human review")
    parser.add_argument("--approve-all-frontier", action="store_true", help="Approve all Gate 1 frontier-verified samples for training")
    parser.add_argument("--feed-sleep", action="store_true", help="Queue rolling passdowns & operator corrections into deep sleep")
    parser.add_argument("--show-passdown", action="store_true", help="Show compact context card from ROLLING_PASSDOWN.md")
    # A-MEM Intermediary Operational Bridge
    parser.add_argument("--sync-amem", action="store_true", help="Sync all approved curation samples to Valkey RAM (:6379) as atomic knowledge cards")
    parser.add_argument("--show-amem", type=str, default=None, nargs="?", const="all", help="Query or list active A-MEM cards generated by the curation bridge")
    # Frontier Failure Trigger Avoidance
    parser.add_argument("--show-triggers", action="store_true", help="List registered Frontier failure triggers and avoidance strategies")
    parser.add_argument("--sync-triggers", action="store_true", help="Sync registered Frontier failure triggers to Valkey RAM as runtime guardrails")

    args = parser.parse_args()

    config_path = args.config
    if not os.path.exists(config_path):
        alt_path = os.path.join(os.path.dirname(__file__), "..", "config", "training_config.yaml")
        if os.path.exists(alt_path):
            config_path = alt_path

    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    # 0. SPECIAL ACTION COMMANDS
    if args.show_triggers:
        from data_ingestion.frontier_trigger_registry import FrontierTriggerRegistry
        processed_dir = config["data_ingestion"].get("dataset_output_dir", "./data/processed")
        reg = FrontierTriggerRegistry(storage_path=os.path.join(processed_dir, "frontier_triggers.json"))
        print(f"\n==================== FRONTIER FAILURE TRIGGERS ({len(reg.triggers)}) ====================")
        for idx, (tid, t) in enumerate(reg.triggers.items()):
            print(f"  [{idx+1}] {tid} ({t.get('domain', 'general')})")
            print(f"      [TRIGGER CONDITION]: {t.get('trigger_condition')}")
            print(f"      [FAILURE MODE]:      {t.get('failure_mode')}")
            print(f"      [AVOIDANCE ACTION]:  {t.get('avoidance_invariant')}")
            print(f"      [VERDICT]:           {t.get('verdict')}")
        print("========================================================================\n")
        return

    if args.sync_triggers:
        from data_ingestion.frontier_trigger_registry import FrontierTriggerRegistry
        processed_dir = config["data_ingestion"].get("dataset_output_dir", "./data/processed")
        reg = FrontierTriggerRegistry(storage_path=os.path.join(processed_dir, "frontier_triggers.json"))
        cnt = reg.sync_to_amem()
        print(f"[SUCCESS] Synced {cnt} Frontier Trigger Avoidance cards into Valkey RAM (:6379).")
        return
    if args.show_passdown:
        mgr = RollingPassdownManager()
        print("\n==================== ROLLING PASSDOWN CONTEXT CARD ====================")
        print(mgr.get_compact_context())
        print("========================================================================\n")
        return

    if args.feed_sleep:
        feeder = RealWorldSleepFeeder()
        print("\n[GROUNDING] Extracting challenges from ROLLING_PASSDOWN.md for deep sleep...")
        ch = feeder.generate_challenges_from_passdown()
        print(f"[GROUNDING] Found {len(ch)} real-world challenges based on operator feedback.")
        feeder.inject_challenges_to_cluster(ch)
        return

    gatekeeper = CurationGatekeeper(
        db_path=os.path.join(config["data_ingestion"].get("dataset_output_dir", "./data/processed"), "curation_registry.json")
    )

    if args.sync_amem:
        print("\n[A-MEM BRIDGE] Synchronizing all approved curation samples into Valkey RAM (:6379)...")
        count = gatekeeper.sync_all_to_amem()
        print(f"[A-MEM BRIDGE] Successfully synced {count} atomic knowledge cards to Valkey RAM.")
        return

    if args.show_amem:
        from data_ingestion.amem_bridge import AMEMBridge
        bridge = AMEMBridge()
        query = args.show_amem
        print("\n==================== A-MEM KNOWLEDGE CARDS ====================")
        if query == "all":
            cards = bridge._local_cards
            print(f"Total Curated Atomic Cards Cached: {len(cards)}")
            for idx, (cid, card) in enumerate(list(cards.items())[:15]):
                print(f"  [{idx+1}] {cid}")
                print(f"      [ATOM]: {card['atom']}")
                print(f"      [TAGS]: {', '.join(card['keywords'][:6])}")
        else:
            print(f"Query: '{query}'")
            injection = bridge.format_memory_injection(query, max_atoms=3)
            print(injection if injection else "No matching atomic cards found.")
        print("================================================================\n")
        return

    if args.review_pending:
        pending = gatekeeper.get_pending_human_reviews()
        print(f"\n[CURATION] {len(pending)} samples waiting for Gate 2 Human-in-the-Loop review:")
        for idx, p in enumerate(pending):
            print(f"  [{idx+1}] ID: {p['id']} | Domain: {p['domain']}")
            print(f"      Prompt: {p['prompt'][:100]}...")
            print(f"      Frontier Verified: {p['frontier_verified']}")
        print("\nUse --approve-all-frontier or programmatic API to stamp approval.")
        return

    if args.approve_all_frontier:
        pending = gatekeeper.get_pending_human_reviews(limit=500)
        approved_cnt = 0
        for p in pending:
            if gatekeeper.human_approve(p["id"], reviewer_notes="Approved via CLI --approve-all-frontier"):
                approved_cnt += 1
        print(f"[CURATION] Successfully approved {approved_cnt} Frontier-audited samples for training weights!")
        print(f"[A-MEM BRIDGE] All {approved_cnt} samples instantly synthesized into in-RAM Atomic Cards (< 35 tokens) in Valkey (:6379)!")
        return

    connector = ClusterBridgeConnector(config_path=args.config)
    connector.update_status("running", 0.05, {"stage": "initialization", "mode": args.mode})

    print("======================================================================")
    print("      GGUF LLM TRAINING PIPELINE (QLoRA & CONTROLLED RL)")
    print(f"  Target: {config['model']['target_model']} | VRAM Envelope: 20GB Total")
    print(f"  Mode: {args.mode.upper()} | Data Source: {args.source.upper()}")
    print("======================================================================")

    # 1. DATA INGESTION
    print("\n[PHASE 1] Data Ingestion & Curation...")
    processed_dir = config["data_ingestion"].get("dataset_output_dir", "./data/processed")
    os.makedirs(processed_dir, exist_ok=True)
    dossiers = []

    if args.source in ["sleep", "all"]:
        archive_dir = config["data_ingestion"].get("thinking_archive_dir", "/opt/cluster-bridge/thinking_archive")
        collector = SleepDossierCollector(archive_dir=archive_dir)
        dossiers = collector.collect_all(limit=50)
        sft_f, dpo_f = collector.export_datasets(dossiers, output_dir=processed_dir)

    if args.source in ["url", "all"] and args.url:
        extractor = ExternalUrlExtractor()
        url_items = extractor.process_url(args.url)
        dossiers.extend(url_items)

    builder = DatasetBuilder(output_dir=processed_dir)
    sft_path, dpo_path = builder.build_unified_datasets(
        uploads_dir=config["data_ingestion"].get("user_upload_dir", "./data/uploads"),
        archive_items=dossiers
    )
    connector.update_status("running", 0.25, {"stage": "data_curated", "sft_samples": len(dossiers)})

    # 2. TRAINING
    adapter_path = None
    if not args.skip_train:
        print("\n[PHASE 2] Executing Training...")
        if args.mode in ["sft", "full"]:
            qlora = QLoRATrainer(config_path=args.config)
            adapter_path = qlora.train(dataset_path=sft_path, model_id=args.model, max_steps=args.steps)
            connector.update_status("running", 0.60, {"stage": "sft_complete", "adapter": adapter_path})

        if args.mode in ["dpo", "full"]:
            rl_trainer = RLAgentTrainer(config_path=args.config)
            adapter_path = rl_trainer.train_dpo(dpo_dataset_path=dpo_path, base_model_id=args.model, max_steps=args.steps)
            connector.update_status("running", 0.75, {"stage": "dpo_complete", "adapter": adapter_path})

    # 3. SAFETY & GOLDEN INVARIANT VERIFICATION
    print("\n[PHASE 3] Safety Guardrails & Invariant Verification...")
    guard = SafetyGuardrails()
    print(f"[INFO] Evaluating model against {len(guard.probes)} Golden Invariants...")
    # Run test verification
    report = guard.run_benchmark(lambda q: "Ornith-1.5 high-precision cluster coordinator with AMD Vulkan acceleration.")
    print(f"[SAFETY VERDICT] Pass Rate: {report['pass_rate'] * 100:.1f}% | Passed: {report['verdict']}")
    connector.update_status("running", 0.85, {"stage": "safety_verified", "pass_rate": report["pass_rate"]})

    # 4. GGUF EXPORT
    if args.export_gguf and adapter_path:
        print("\n[PHASE 4] Merging LoRA & Exporting GGUF...")
        merger = LoRAMerger(config_path=args.config)
        hf_merged = merger.merge(
            base_model_id=args.model or config["model"]["hf_base_model"],
            adapter_path=adapter_path
        )
        exporter = GGUFExporter(config_path=args.config)
        if args.quant == "all":
            gguf_files = exporter.export_all(hf_merged)
        else:
            f16 = exporter.convert_hf_to_gguf(hf_merged)
            gguf_files = [exporter.quantize(f16, quant_type=args.quant)]
        connector.update_status("running", 0.95, {"stage": "gguf_exported", "files": gguf_files})

    # 5. PROMOTION
    if args.promote:
        print(f"\n[PHASE 5] Safe Deployment to Cluster ({args.promote.upper()})...")
        # Find latest exported GGUF
        out_gguf = f"./output/gguf/ornith-1.5-9b-trained-{config['export']['quantization_targets'][0]}.gguf"
        if os.path.exists(out_gguf):
            connector.promote_to_cluster(out_gguf, role=args.promote)
        else:
            print(f"[WARN] Staged GGUF {out_gguf} not found for promotion.")

    connector.update_status("completed", 1.0, {"stage": "done"})
    print("\n======================================================================")
    print("               PIPELINE EXECUTION COMPLETED SUCCESSFULLY              ")
    print("======================================================================")

if __name__ == "__main__":
    main()
